Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
    using crud.salesorder.Components;
    using crud.salesorder.Models;
    using Kendo.Mvc.Extensions;
    using Kendo.Mvc.UI;
    using MongoDB.Bson;
    using MongoDB.Driver;

namespace crud.salesorder.Controllers
{
    public class MasterDataController : Controller
    {
        string constr = ConfigurationManager.AppSettings["connectionString"];
        string databaseName = ConfigurationManager.AppSettings["MongoDatabaseName"];

        // GET: MasterData
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddItem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddItem(Goods goods)
        {
            if (ModelState.IsValid)
            {
                var Client = new MongoClient(constr);
                var DB = Client.GetDatabase(databaseName);
                var collection = DB.GetCollection<Goods>("tGoods");

                //goods._id = ObjectId.GenerateNewId();
                goods.id = new Sequence() { }.GetNextSequenceValue("tGoods", databaseName);
                goods.crtAt = GlobalFunctions.GetIPAddress();
                goods.crtBy = "User1";
                goods.crtOn = DateTime.Now;

                collection.InsertOneAsync(goods);
                return RedirectToAction("AddItem");
            }
            return View();
        }

        public ActionResult EditItem (string id)
        {
            var client = new MongoClient(constr);
            var db = client.GetDatabase(databaseName);
            var collection = db.GetCollection<Goods>("tGoods");
            var filter = Builders<Goods>.Filter.Eq("id", id);
            var result = collection.Find(filter).Single();

            return View(result);
        }

        [HttpPost]
        public ActionResult EditItem(string id, Goods goods)
        {            
            try
            {
                var client = new MongoClient(constr);
                var db = client.GetDatabase(databaseName);
                var collection = db.GetCollection<Goods>("tGoods");
                var filter = Builders<Goods>.Filter.Eq("id", id);

                goods.uptAt = GlobalFunctions.GetIPAddress();
                goods.uptBy = "User1";
                goods.uptOn = DateTime.Now;

                var set = Builders<Goods>.Update
                    .Set("itemName", goods.itemName)
                    .Set("price", goods.price)
                    .Set("uptAt", goods.uptAt)
                    .Set("uptBy", goods.uptBy)
                    .Set("uptOn", goods.uptOn);
                collection.FindOneAndUpdateAsync(filter, set);
                return RedirectToAction("IndexItem");
            }
            catch(Exception ex)
            {
                return View();
            }            
        }
        public ActionResult IndexItem()
        {
            return View();
        }
        public ActionResult ReadItem([DataSourceRequest] DataSourceRequest request)
        {
            var Client = new MongoClient(constr);
            var DB = Client.GetDatabase(databaseName);
            var collection = DB.GetCollection<Goods>("tGoods").Find(new BsonDocument()).ToList();
            return Json(collection.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateItem([DataSourceRequest] DataSourceRequest request, Goods goods)
        {
            var Client = new MongoClient(constr);
            var DB = Client.GetDatabase(databaseName);
            var collection = DB.GetCollection<Goods>("tGoods");
            var filter = Builders<Goods>.Filter.Eq("id", goods.id);
            var result = collection.Find(filter).Single();

            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DestroyItem([DataSourceRequest] DataSourceRequest request, Goods goods)
        {
            if(goods != null)
            {
                var Client = new MongoClient(constr);
                var DB = Client.GetDatabase(databaseName);
                var collection = DB.GetCollection<Goods>("tGoods");
                var filter = Builders<Goods>.Filter.Eq("id", goods.id);
                var deleteRecord = collection.DeleteOneAsync(filter);
            }
            return Json(new[] { goods }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult AddBizPartner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBizPartner(BizPartner bizPartner)
        {
            if (ModelState.IsValid)
            {
                var Client = new MongoClient(constr);
                var DB = Client.GetDatabase(databaseName);
                var collection = DB.GetCollection<BizPartner>("tBizPartner");

                //goods._id = ObjectId.GenerateNewId();
                bizPartner.id = new Sequence() { }.GetNextSequenceValue("tBizPartner", databaseName);
                bizPartner.crtAt = GlobalFunctions.GetIPAddress();
                bizPartner.crtBy = "User1";
                bizPartner.crtOn = DateTime.Now;

                collection.InsertOneAsync(bizPartner);
                return RedirectToAction("AddItem");
            }
            return View();
        }
        public ActionResult EditBizPartner(string id)
        {
            var client = new MongoClient(constr);
            var db = client.GetDatabase(databaseName);
            var collection = db.GetCollection<BizPartner>("tBizPartner");
            var filter = Builders<BizPartner>.Filter.Eq("id", id);
            var result = collection.Find(filter).Single();

            return View(result);
        }
        [HttpPost]
        public ActionResult EditBizPartner(string id, BizPartner bizPartner)
        {
            try
            {
                var client = new MongoClient(constr);
                var db = client.GetDatabase(databaseName);
                var collection = db.GetCollection<BizPartner>("tBizPartner");
                var filter = Builders<BizPartner>.Filter.Eq("id", id);

                bizPartner.uptAt = GlobalFunctions.GetIPAddress();
                bizPartner.uptBy = "User1";
                bizPartner.uptOn = DateTime.Now;

                var set = Builders<BizPartner>.Update
                    .Set("nameBizPartner", bizPartner.nameBizPartner)                    
                    .Set("uptAt", bizPartner.uptAt)
                    .Set("uptBy", bizPartner.uptBy)
                    .Set("uptOn", bizPartner.uptOn);
                collection.FindOneAndUpdateAsync(filter, set);
                return RedirectToAction("IndexItem");
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using crud.salesorder.Components;
using crud.salesorder.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using MongoDB.Bson;
using MongoDB.Driver;

namespace crud.salesorder.Controllers
{
    public class TransactionController : Controller
    {
        string constr = ConfigurationManager.AppSettings["connectionString"];
        string databaseName = ConfigurationManager.AppSettings["MongoDatabaseName"];

        // GET: Transaction
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddSalesOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddSalesOrder(SalesOrderHeader salesOrderHeader, List<SalesOrderDetail> details)
        {
            var Client = new MongoClient(constr);
            var DB = Client.GetDatabase(databaseName);
            var collection = DB.GetCollection<SalesOrderHeader>("tSalerOrderHeader");

            salesOrderHeader.id = new Sequence() { }.GetNextSequenceValue("tSalesOrderHeader", databaseName);
            salesOrderHeader.status = 0; //Draft
            salesOrderHeader.crtAt = GlobalFunctions.GetIPAddress();
            salesOrderHeader.crtBy = "User1";
            salesOrderHeader.crtOn = DateTime.Now;            

            foreach (var detail in details)
            {
                var collectionDetail = DB.GetCollection<SalesOrderDetail>("tSalesOrderDetail");
                detail.idSalesOrderHeader = salesOrderHeader.id;
                detail.id = new Sequence() { }.GetNextSequenceValue("tSalerOrderDetail", databaseName);

                collectionDetail.InsertOneAsync(detail);
            }
            collection.InsertOneAsync(salesOrderHeader);

            return View();
        }      

        public ActionResult AddSalesOrderDetail(int? i)
        {
            ViewBag.i = i;
            return PartialView();
        }

        public ActionResult SalesOrder()
        {
            return View();
        }
        public ActionResult ReadSalesOrder([DataSourceRequest] DataSourceRequest request)
        {
            var Client = new MongoClient(constr);
            var db = Client.GetDatabase(databaseName);
            var collection = db.GetCollection<SalesOrderHeader>("tSalerOrderHeader").Find(new BsonDocument()).ToList();
            return Json(collection.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ReadSalesOrderDetail([DataSourceRequest] DataSourceRequest request)
        {
            var Client = new MongoClient(constr);
            var db = Client.GetDatabase(databaseName);
            var collection = db.GetCollection<SalesOrderDetail>("tSalesOrderDetail").Find(new BsonDocument()).ToList();
            return Json(collection.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - My Telerik MVC Application</title>
    <link href="https://kendo.cdn.telerik.com/2020.3.1021/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.3.1021/js/kendo.aspnetmvc.min.js"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
</head>
<body class="k-content">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid d-flex justify-content-between p-0">
            <h1 class="navbar-brand d-flex align-items-center">Project Title</h1>
            <button id="configure" class="k-rpanel-toggle k-button k-primary btn-toggle">
                <span class="k-icon k-i-menu"></span>
            </button>
        </div>
    </nav>

    <div id="responsive-panel" class="navbar navbar-dark bg-light">
        <ul id="menu" style="width: 100%">
            <li>
                @Html.ActionLink("Goods", "IndexItem", "MasterData")
            </li>
            <li disabled="disabled">
                Biz Partner
            </li>
            <li>
                @Html.ActionLink("Sales Order","SalesOrder","Transaction")
            </li>
            <li disabled="disabled">
                Disabled Item
            </li>
        </ul>
    </div>

    <main>
        <div class="container-fluid">
            @RenderBody()
        </div>
    </main>

    <footer class="footer text-center d-flex align-items-center">
        <div class="container-fluid">
            <p class="text-muted">Copyright © @DateTime.Now.Year Progress Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.</p>
        </div>
    </footer>

    <script>
        $(document).ready(function () {
            $("#responsive-panel").kendoResponsivePanel({
                breakpoint: 768,
                autoClose: false,
                orientation: "top"
            });
            $("#menu").kendoMenu();
        });
        function onclick(e) {
            $("#responsive-panel").getKendoResponsivePanel().toggle();
        }
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>